name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.4'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'
        modules: 'qtopengl qtopenglwidgets'

    - name: Vcpkg install
      run: vcpkg install tbb:x64-windows

    - name: Check out
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Pack
      working-directory: ${{github.workspace}}/build
      run: cpack -C ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          ${{github.workspace}}/build/*.exe
